// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AddToWaitlist(ctx context.Context, arg AddToWaitlistParams) error
	ArchiveChatSession(ctx context.Context, arg ArchiveChatSessionParams) (ChatSession, error)
	CountPublicSessionMessages(ctx context.Context, sessionID uuid.UUID) (int64, error)
	CountSessionMessages(ctx context.Context, arg CountSessionMessagesParams) (int64, error)
	CountUserChatSessions(ctx context.Context, userID uuid.UUID) (int64, error)
	CreateAuthSession(ctx context.Context, arg CreateAuthSessionParams) (AuthSession, error)
	CreateChatMessage(ctx context.Context, arg CreateChatMessageParams) (ChatMessage, error)
	CreateChatSession(ctx context.Context, arg CreateChatSessionParams) (ChatSession, error)
	CreateEmailVerification(ctx context.Context, arg CreateEmailVerificationParams) (EmailVerification, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeletePublicSessionMessages(ctx context.Context, sessionID uuid.UUID) error
	DeleteSessionMessages(ctx context.Context, arg DeleteSessionMessagesParams) error
	GetAllWaitlist(ctx context.Context) ([]Waitlist, error)
	GetAuthSession(ctx context.Context, id uuid.UUID) (AuthSession, error)
	GetChatMessage(ctx context.Context, arg GetChatMessageParams) (ChatMessage, error)
	GetChatSession(ctx context.Context, arg GetChatSessionParams) (ChatSession, error)
	GetLastPublicSessionMessage(ctx context.Context, sessionID uuid.UUID) (ChatMessage, error)
	GetLastSessionMessage(ctx context.Context, arg GetLastSessionMessageParams) (ChatMessage, error)
	GetPublicChatMessage(ctx context.Context, id uuid.UUID) (ChatMessage, error)
	GetPublicChatSession(ctx context.Context, id uuid.UUID) (ChatSession, error)
	GetUser(ctx context.Context, id uuid.UUID) (User, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	// get all public sessions
	ListPublicChatSessions(ctx context.Context) ([]ChatSession, error)
	ListPublicSessionMessages(ctx context.Context, sessionID uuid.UUID) ([]ChatMessage, error)
	ListSessionMessages(ctx context.Context, arg ListSessionMessagesParams) ([]ChatMessage, error)
	ListUserChatSessions(ctx context.Context, userID uuid.UUID) ([]ChatSession, error)
	ListUserChatSessionsByIP(ctx context.Context, ipAddress string) ([]ChatSession, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	UpdateChatSessionTitle(ctx context.Context, arg UpdateChatSessionTitleParams) (ChatSession, error)
	UpdateLastMessageTime(ctx context.Context, arg UpdateLastMessageTimeParams) (ChatSession, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
	VerifyEmail(ctx context.Context, arg VerifyEmailParams) (EmailVerification, error)
}

var _ Querier = (*Queries)(nil)
